### ISSUE TITLE
Not getting good results ?

### ISSUE THREAD

**Issue by alan-ai-learner** [frankplus/meena-chatbot#2]
hi @frankplus  first of all thanks for your work, so I use your Jupyter notebook to train the model on the open subtitles English dataset but not getting good results.
I trained it for like 3 hours on colab pro gpu, but the training goes on then i stopped it and tried the code for testing the model . but seems like the results were not that good.
Can you you please suggest some better way to make mods of the meena, or you can guide me how can use your repo to use efficiently.

**Comment by frankplus** [comment]
I think 3 hours on colab is really not enough to train a decent model on colab, I trained it for several days and still can be improved a lot.
You could play around with the hyperparameters, adjusting the size of the model or dataset. 
If you train it in the english language, you may need to change the `preprocess_sentence(sentence)` function for example by adding replacement of the apostrophe: 
```
don't -> do not
you're -> you are
you've -> you have
...
```

**Comment by alan-ai-learner** [comment]
@frankplus thanks for you response, so where have you trained it for several days (can you make sure the number of days approximately will be best.) and is it  possible that the check points that are saved during the training  can be used for the retraining from the last point ,is there any way in your code where I can make the changes and do that. What changes can be made for doing that,  because I haven't use T2T, this is my first time so pls help.
Thanks
